---
apiVersion: v1
kind: Namespace
metadata:
  name: cadang-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadang-deploy
  namespace: cadang-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cadang-app
  template:
    metadata:
      labels:
        app: cadang-app
    spec:
      containers:
      - name: cadang-container
        image: crystallsy/nov11-dov:v1
        ports:
        - containerPort: 3000   # Caddy listens on port 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cadang-svc
  namespace: cadang-ns
spec:
  type: LoadBalancer
  selector:
    app: cadang-app
  ports:
  - protocol: TCP
    port: 80        # Exposed service port
    targetPort: 3000  # Forward to containerâ€™s Caddy port
